ARG BASE_IMAGE_REF="ghcr.io/projectbluefin/dakota:stable@sha256:5989c44875101aaf8928f36360c8434f90ca485cb67d07ec07d7196c44a61f6c"

FROM scratch AS ctx
COPY build/10-dakota.sh /build/10-dakota.sh
COPY build/20-final-metadata.sh /build/20-final-metadata.sh
COPY custom/ujust /custom/ujust
COPY custom/system_files/etc/fonts/conf.d/60-dudley-monospace.conf /custom/system_files/etc/fonts/conf.d/60-dudley-monospace.conf
COPY custom/system_files/usr/share/glib-2.0/schemas/zz1-dudley-terminal.gschema.override /custom/system_files/usr/share/glib-2.0/schemas/zz1-dudley-terminal.gschema.override
COPY custom/system_files/usr/share/ublue-os/user-setup.hooks.d/10-wallpaper-enforcement.sh /custom/system_files/usr/share/ublue-os/user-setup.hooks.d/10-wallpaper-enforcement.sh
COPY --from=ghcr.io/joshyorko/dsb-common:latest@sha256:4149fcc8ea776d6696bbeed0dd7e77a8b0a2d08938747a48be629449f87f637d /system_files/shared /oci/dsb-common/shared
COPY --from=ghcr.io/joshyorko/dsb-common:latest@sha256:4149fcc8ea776d6696bbeed0dd7e77a8b0a2d08938747a48be629449f87f637d /system_files/dudley /oci/dsb-common/dudley

FROM ${BASE_IMAGE_REF}
ARG BASE_IMAGE_REF
ARG FINAL_IMAGE_REF="ghcr.io/joshyorko/dudley-os:dakota"
ARG SHA_HEAD_SHORT="unknown"
ARG VSCODE_REFRESH_TOKEN

RUN --mount=type=bind,from=ctx,source=/,target=/ctx \
    --mount=type=tmpfs,dst=/tmp \
    /ctx/build/10-dakota.sh

RUN bootc container lint
