ARG BASE_IMAGE_REF="ghcr.io/projectbluefin/dakota:stable@sha256:2aa538b4fd31454820ef271fd911291bae5aeed68957faa4cff3f4389c0dd00b"

FROM scratch AS ctx
COPY build/10-dakota.sh /build/10-dakota.sh
COPY build/20-final-metadata.sh /build/20-final-metadata.sh
COPY custom/ujust /custom/ujust
COPY custom/system_files/etc/fonts/conf.d/60-dudley-monospace.conf /custom/system_files/etc/fonts/conf.d/60-dudley-monospace.conf
COPY custom/system_files/usr/share/glib-2.0/schemas/zz1-dudley-terminal.gschema.override /custom/system_files/usr/share/glib-2.0/schemas/zz1-dudley-terminal.gschema.override
COPY custom/system_files/usr/share/ublue-os/user-setup.hooks.d/10-wallpaper-enforcement.sh /custom/system_files/usr/share/ublue-os/user-setup.hooks.d/10-wallpaper-enforcement.sh
COPY --from=ghcr.io/joshyorko/dsb-common:latest@sha256:3d09142b48b7dad0902bac5a06b731d6c48fcd10c66f44d1b7968ef8416e9582 /system_files/shared /oci/dsb-common/shared
COPY --from=ghcr.io/joshyorko/dsb-common:latest@sha256:3d09142b48b7dad0902bac5a06b731d6c48fcd10c66f44d1b7968ef8416e9582 /system_files/dudley /oci/dsb-common/dudley

FROM ${BASE_IMAGE_REF}
ARG BASE_IMAGE_REF
ARG FINAL_IMAGE_REF="ghcr.io/joshyorko/dudley-os:dakota"
ARG SHA_HEAD_SHORT="unknown"
ARG VSCODE_REFRESH_TOKEN

RUN --mount=type=bind,from=ctx,source=/,target=/ctx \
    --mount=type=tmpfs,dst=/tmp \
    /ctx/build/10-dakota.sh

RUN bootc container lint
