# Dudley development tools, including the legacy cloud-native set
tap "joshyorko/tools"
tap "k0sproject/tap"

brew "ansible"
brew "cdk8s"
brew "dagger"
brew "dialog"
brew "grype"
brew "hadolint"
brew "helm"
brew "k0sproject/tap/k0sctl"
brew "k3sup"
brew "k9s"
brew "kind"
brew "kubectl"
brew "kubectx"
brew "kubernetes-cli"
brew "node"
brew "python@3.13"
brew "python@3.14"
brew "rancher-cli"
cask "joshyorko/tools/rcc"
brew "syft"
brew "trivy"
brew "uv"
