name: Cleanup Old Images

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}

jobs:
  delete-older-than-30:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Delete Images Older Than 90 Days
        uses: projectbluefin/actions/bootc-build/ghcr-cleanup@4d3b97eb9760539d2b4a8f2a495db0ec3bf9e8a0 # v1
        with:
          packages: dudley-os
          older-than: 30 days
          keep-n-tagged: "7"
          keep-n-untagged: "7"
          github-token: ${{ secrets.GITHUB_TOKEN }}
