name: Cleanup Old Images

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}

jobs:
  delete-older-than-90:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Delete Images Older Than 90 Days
        uses: projectbluefin/actions/bootc-build/ghcr-cleanup@a075dd84fa6adba08f7fe16a06a842098076fda0 # v1
        with:
          packages: dudley-os
          older-than: 90 days
          keep-n-tagged: "7"
          keep-n-untagged: "7"
          github-token: ${{ secrets.GITHUB_TOKEN }}
