name: Cleanup Old Images

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}

jobs:
  delete-older-than-90:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Delete Images Older Than 90 Days
        uses: projectbluefin/actions/bootc-build/ghcr-cleanup@793eea3015e29223e60fa0ffc7ceb47ca8a1d250 # v1
        with:
          packages: dudley-os
          older-than: 90 days
          keep-n-tagged: "7"
          keep-n-untagged: "7"
          github-token: ${{ secrets.GITHUB_TOKEN }}
